%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1616
image_height: 1232
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 410.777504
   fy: 410.777504
   cx: 805.879152
   cy: 613.277472